
services:
  auth-backend:
    build:
      context: ./backend/auth-service
      dockerfile: dockerfile
    container_name: auth-backend
    restart: always
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - app_net
    depends_on:
      auth-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    
  products-backend:
    build:
      context: ./backend/products-service
      dockerfile: dockerfile
    container_name: products-backend
    restart: always
    env_file:
      - .env
    expose:
      - "8002"
    networks:
      - app_net
    depends_on:
      products-postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  reviews-backend:
    build:
      context: ./backend/reviews-service
      dockerfile: dockerfile
    container_name: reviews-backend
    restart: always
    env_file:
      - .env
    expose:
      - "8003"
    networks:
      - app_net
    depends_on:
      reviews-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  reviews-consumer:
    build:
      context: ./backend/reviews-service
      dockerfile: dockerfile
    container_name: reviews-consumer
    restart: always
    env_file:
      - .env
    command: ["python", "run_consumer.py"]
    networks:
      - app_net
    depends_on:
      reviews-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: dockerfile
    container_name: notification-service
    restart: always
    env_file:
      - .env
    networks:
      - app_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started

  api-gateway:
    image: nginx:1.27-alpine
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - auth-backend
    networks:
      - app_net

  auth-postgres:
    image: postgres:17-alpine
    container_name: auth-postgres
    restart: always
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
    networks:
      - app_net
    ports:
      - "${AUTH_SERVICE_POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_POSTGRES_USER} -d ${AUTH_SERVICE_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  products-postgres:
    image: postgres:17-alpine
    container_name: products-postgres
    restart: always
    volumes:
      - products-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PRODUCTS_SERVICE_POSTGRES_DB_NAME}
      POSTGRES_USER: ${PRODUCTS_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_SERVICE_POSTGRES_PASSWORD}
    networks:
      - app_net
    ports:
      - "${PRODUCTS_SERVICE_POSTGRES_EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PRODUCTS_SERVICE_POSTGRES_USER} -d ${PRODUCTS_SERVICE_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  reviews-postgres:
    image: postgres:17-alpine
    container_name: reviews-postgres
    restart: always
    volumes:
      - reviews-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${REVIEWS_SERVICE_POSTGRES_DB_NAME}
      POSTGRES_USER: ${REVIEWS_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REVIEWS_SERVICE_POSTGRES_PASSWORD}
    networks:
      - app_net
    ports:
      - "${REVIEWS_SERVICE_POSTGRES_EXTERNAL_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${REVIEWS_SERVICE_POSTGRES_USER} -d ${REVIEWS_SERVICE_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  auth-redis:
    image: redis:8.0-alpine
    container_name: auth-redis
    networks:
      - app_net
    volumes:
      - auth-redis:/data
    environment:
      - REDIS_PASSWORD=${AUTH_SERVICE_REDIS_PASSWORD}
    command: redis-server --requirepass ${AUTH_SERVICE_REDIS_PASSWORD} --appendonly yes
    ports:
      - "${AUTH_SERVICE_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${AUTH_SERVICE_REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  products-redis:
    image: redis:8.0-alpine
    container_name: products-redis
    networks:
      - app_net
    volumes:
      - products-redis:/data
    environment:
      - REDIS_PASSWORD=${PRODUCTS_SERVICE_REDIS_PASSWORD}
    command: redis-server --requirepass ${PRODUCTS_SERVICE_REDIS_PASSWORD} --appendonly yes
    ports:
      - "${PRODUCTS_SERVICE_REDIS_EXTERNAL_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${PRODUCTS_SERVICE_REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      auth-postgres:
        condition: service_healthy

  redis_monitoring:
    image: redis/redisinsight:3.0.3
    container_name: redis_monitoring
    restart: always
    ports:
      - "5540:5540"
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - app_net
    depends_on:
      - auth-backend
      - products-backend

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - prometheus

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="http://localhost:5601,http://127.0.0.1:5601"
      - http.cors.allow-headers=X-Requested-With,Content-Type,Content-Length,Authorization
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "${ELASTIC_USER}:${ELASTIC_PASSWORD}", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  elasticvue:
    image: cars10/elasticvue:1.15.0
    container_name: elasticvue
    restart: always
    ports:
      - "5601:8080"
    networks:
      - app_net
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app_net

volumes:
  auth-postgres-data:
  products-postgres-data:
  reviews-postgres-data:
  products-redis:
  auth-redis:
  elasticsearch-data:
  rabbitmq-data:
  prometheus-data:
  grafana-data:

networks:
  app_net:
    driver: bridge
