
services:
  auth-backend:
    build:
      context: ./backend/auth-service
      dockerfile: dockerfile
    container_name: auth-backend
    restart: always
    env_file:
      - .env
    expose:
      - "8001"
    networks:
      - app_net
    depends_on:
      auth-postgres:
        condition: service_healthy

  api-gateway:
    image: nginx:1.27-alpine
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - auth-backend
    networks:
      - app_net

  auth-postgres:
    image: postgres:17-alpine
    container_name: auth-postgres
    restart: always
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_POSTGRES_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_POSTGRES_PASSWORD}
    networks:
      - app_net
    ports:
      - "${AUTH_SERVICE_POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_POSTGRES_USER} -d ${AUTH_SERVICE_POSTGRES_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      auth-postgres:
        condition: service_healthy

  redis_monitoring:
    image: redis/redisinsight:3.0.3
    container_name: redis_monitoring
    restart: always
    ports:
      - "5540:5540"
    networks:
      - app_net
  
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - app_net
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    restart: always
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - app_net
    depends_on:
      - prometheus

volumes:
  auth-postgres-data:
  prometheus-data:
  grafana-data:

networks:
  app_net:
    driver: bridge
