
global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi-services'
    metrics_path: /api/metrics 
    scrape_interval: 10s
    static_configs:
      - targets: ['auth-backend:8001']
        labels:
          service: 'auth-service'

      - targets: ['products-backend:8002']
        labels:
          service: 'products-service'
