
[project]
name = "reviews-service"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=10.0.1",
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "mypy>=2.3.1",
    "prometheus-fastapi-instrumentator>=8.1.0",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt[crypto]>=2.14.0",
    "redis>=8.1.0",
    "ruff>=0.16.7",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.53.0",
]

[tool.ruff]
line-length = 120
exclude = [".venv", "venv", ".env", "env", "alembic", "migrations"]

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
fixable = ["ALL"]

[tool.mypy]
python_version = "3.12"
strict = true
explicit_package_bases = true
exclude = [".venv", "venv", ".env", "env", "alembic", "migrations"]
